import '~/styles/globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '~/components/header'
import { cn } from '~/utils/cn'

const inter = Inter({
  variable: '--font-sans',
  display: 'optional',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-[#1D1D21] font-sans text-sm antialiased selection:bg-blue-800 selection:text-white',
          inter.variable,
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
