import '~/styles/globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Footer } from '~/components/footer'
import { Header } from '~/components/header'
import { cn } from '~/utils/cn'

const inter = Inter({
  variable: '--font-sans',
  display: 'optional',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'flex min-h-screen flex-col items-center bg-[#19191C] font-sans text-[#C3C3C6] text-sm antialiased selection:bg-blue-800 selection:text-white',
          inter.variable,
        )}
      >
        <Header />
        <main className="mx-auto w-full grow">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
